# Generated by Django 4.2.4 on 2023-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userinfo_age_userinfo_sex_userinfo_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=2, verbose_name='是否为管理员'),
        ),
    ]
