# Generated by Django 4.2.4 on 2023-08-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, '锁'), (2, '非锁')], default=2, verbose_name='状态'),
        ),
    ]
